### ISSUE TITLE
Unrar file

### ISSUE THREAD

**Issue by ariran5** [codedread/bitjs#13]
Hi, how I can unrar file with your code?

**Comment by ariran5** [comment]
In node's with streams

**Comment by codedread** [comment]
Sorry, I do not use nodejs with streams.  Do the examples in the readme not give you enough context?  https://github.com/codedread/bitjs/

**Comment by codedread** [comment]
I don't personally use unrarring functionality in node with streams, so I don't plan on documenting this. If someone cares to, they can reopen this bug and attach a PR
