### ISSUE TITLE
Look at CompressionStream for zip

### ISSUE THREAD

**Issue by codedread** [codedread/bitjs#40]
https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API

**Comment by codedread** [comment]
and https://caniuse.com/mdn-api_compressionstream_compressionstream_deflate

**Comment by sntran** [comment]
For a reference, zip.js has an implementation with CompressionStream: https://gildas-lormeau.github.io/zip.js/

**Comment by codedread** [comment]
Hopefully fixed. Will be part of the 1.2.2 release.
