### ISSUE TITLE
Decompressing from node js and not the browser

### ISSUE THREAD

**Issue by Inalegwu** [codedread/bitjs#44]
Having looked over the examples , it's quite obvious that bitjs is intended to be called from the browser context , but would it be possible to call it from a node js process instead as I plan on using this in an electron application

**Comment by codedread** [comment]
I think this feature request roughly equates to [these TODOs](https://github.com/search?q=repo%3Acodedread%2Fbitjs+%22TODO%3A+Make+this+a+plain+ES+Module+and+then+write+a+thin+wrapper+around+it+for+Worker-ization%22&type=code) which should make Web Workers optional. Perhaps an optional argument in the constructors for Unzipper, etc to provide the Worker implementation (with the ability to have none) ?

**Comment by codedread** [comment]
It would also address [this TODO](https://github.com/codedread/bitjs/blob/2ed482879f9032543fc585910944848a53b96bb4/archive/decompress-internal.js#L324)

**Comment by codedread** [comment]
I think this is complete, but I won't close the bug just yet (nor release an official version). Would you mind testing it at head?

I used the following NodeJS code to test it: https://github.com/codedread/bitjs#a-nodejs-example

**Comment by codedread** [comment]
With a couple tweaks to make a better worker URL, it works in Deno and Bun too

**Comment by Inalegwu** [comment]
> I think this is complete, but I won't close the bug just yet (nor release an official version). Would you mind testing it at head?
> 
> 
> 
> I used the following NodeJS code to test it: https://github.com/codedread/bitjs#a-nodejs-example

I wouldn't mind testing it actually as I've been waiting patiently for this 😅

Sorry for the extremely late reply as well
